# @package _global_

defaults:
  - robot_base
  

robot:
  # Observation parameters
  num_bodies: 24
  dof_obs_size: 69
  actions_dim: 69
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  
  key_bodies: ["L_Ankle", "R_Ankle", "R_Wrist", "L_Wrist"]
  contact_bodies: [ "L_Ankle", "R_Ankle", "R_Toe", "L_Toe" ]
  right_foot_name: "R_Ankle"
  left_foot_name: "L_Ankle"
  foot_name: "Ankle"
  knee_name: "Knee"
  has_upper_body_dof: True
  has_torso: True
  torso_name: "Pelvis"
  # DFS order (isaacgym order)
  dof_names: ['L_Hip_x', 
              'L_Hip_y', 
              'L_Hip_z', 
              'L_Knee_x', 
              'L_Knee_y',
              'L_Knee_z', 
              'L_Ankle_x', 
              'L_Ankle_y', 
              'L_Ankle_z', 
              'L_Toe_x',
              'L_Toe_y', 
              'L_Toe_z', 
              'R_Hip_x', 
              'R_Hip_y', 
              'R_Hip_z', 
              'R_Knee_x', 
              'R_Knee_y',
              'R_Knee_z', 
              'R_Ankle_x', 
              'R_Ankle_y', 
              'R_Ankle_z', 
              'R_Toe_x',
              'R_Toe_y', 
              'R_Toe_z', 
              'Torso_x',
              'Torso_y', 
              'Torso_z', 
              'Spine_x',
              'Spine_y', 
              'Spine_z', 
              'Chest_x',
              'Chest_y', 
              'Chest_z', 
              'Neck_x',
              'Neck_y', 
              'Neck_z', 
              'Head_x',
              'Head_y', 
              'Head_z', 
              'L_Thorax_x',
              'L_Thorax_y', 
              'L_Thorax_z', 
              'L_Shoulder_x',
              'L_Shoulder_y', 
              'L_Shoulder_z', 
              'L_Elbow_x',
              'L_Elbow_y', 
              'L_Elbow_z', 
              'L_Wrist_x',
              'L_Wrist_y', 
              'L_Wrist_z', 
              'L_Hand_x',
              'L_Hand_y', 
              'L_Hand_z', 
              'R_Thorax_x',
              'R_Thorax_y', 
              'R_Thorax_z', 
              'R_Shoulder_x',
              'R_Shoulder_y', 
              'R_Shoulder_z', 
              'R_Elbow_x',
              'R_Elbow_y', 
              'R_Elbow_z', 
              'R_Wrist_x',
              'R_Wrist_y', 
              'R_Wrist_z', 
              'R_Hand_x',
              'R_Hand_y', 
              'R_Hand_z', ]
              
    
  upper_dof_names: ['Spine_x',
                    'Spine_y', 
                    'Spine_z', 
                    'Chest_x',
                    'Chest_y', 
                    'Chest_z', 
                    'Neck_x',
                    'Neck_y', 
                    'Neck_z', 
                    'Head_x',
                    'Head_y', 
                    'Head_z', 
                    'L_Thorax_x',
                    'L_Thorax_y', 
                    'L_Thorax_z', 
                    'L_Shoulder_x',
                    'L_Shoulder_y', 
                    'L_Shoulder_z', 
                    'L_Elbow_x',
                    'L_Elbow_y', 
                    'L_Elbow_z', 
                    'L_Wrist_x',
                    'L_Wrist_y', 
                    'L_Wrist_z', 
                    'L_Hand_x',
                    'L_Hand_y', 
                    'L_Hand_z', 
                    'R_Thorax_x',
                    'R_Thorax_y', 
                    'R_Thorax_z', 
                    'R_Shoulder_x',
                    'R_Shoulder_y', 
                    'R_Shoulder_z', 
                    'R_Elbow_x',
                    'R_Elbow_y', 
                    'R_Elbow_z', 
                    'R_Wrist_x',
                    'R_Wrist_y', 
                    'R_Wrist_z', 
                    'R_Hand_x',
                    'R_Hand_y', 
                    'R_Hand_z', ]
  
  lower_dof_names: ['L_Hip_x', 
                    'L_Hip_y', 
                    'L_Hip_z', 
                    'L_Knee_x', 
                    'L_Knee_y',
                    'L_Knee_z', 
                    'L_Ankle_x', 
                    'L_Ankle_y', 
                    'L_Ankle_z', 
                    'L_Toe_x',
                    'L_Toe_y', 
                    'L_Toe_z', 
                    'R_Hip_x', 
                    'R_Hip_y', 
                    'R_Hip_z', 
                    'R_Knee_x', 
                    'R_Knee_y',
                    'R_Knee_z', 
                    'R_Ankle_x', 
                    'R_Ankle_y', 
                    'R_Ankle_z', 
                    'R_Toe_x',
                    'R_Toe_y', 
                    'R_Toe_z',]
  # waist_dof_names: ['Torso_x', 'Torso_y', 'Torso_z', ]
  
  
  # DOF properties
  dof_pos_lower_limit_list: [-1.571, -1.571 -1.571, -3.141, -0.098, -0.098, -1.571, -1.571 -1.571, -1.571, -0.785, -0.785, -1.571, -1.571 -1.571, -3.141, -0.098, -0.098, -1.571, -1.571 -1.571, -1.571, -0.785, -0.785, -1.047, -1.047 -1.047, -1.047, -1.047 -1.047, -1.047, -1.047 -1.047, -3.141, -3.141, -3.141, -1.571, -1.571, -1.571, -3.141, -3.141, -3.141, -3.141, -3.141, -3.141, -12.566, -12.566, -12.566, -3.141, -3.141, -3.141, -3.141, -3.141, -3.141, -3.141, -3.141, -3.141, -12.566, -12.566, -12.566, -3.141, -3.141, -3.141, ]
  dof_pos_upper_limit_list: [1.571,  1.571, 1.571,  3.141, 0.098, 0.098, 1.571,  1.571, 1.571, 1.571, 0.785, 0.785, 1.571,  1.571, 1.571,  3.141, 0.098, 0.098, 1.571,  1.571, 1.571, 1.571, 0.785, 0.785, 1.047, 1.047, 1.047, 1.047, 1.047, 1.047, 1.047, 1.047, 1.047, 3.141, 3.141, 3.141, 1.571, 1.571, 1.571, 3.141, 3.141, 3.141, 3.141, 3.141, 3.141, 12.566, 12.566, 12.566, 3.141, 3.141, 3.141, 3.141, 3.141, 3.141, 3.141, 3.141, 3.141, 12.566, 12.566, 12.566, 3.141, 3.141, 3.141, ]
  # dof_vel_limit_list:       [23.,   23.,    23.,   14.,   9.,          23.,  23.,   23.,  14.,     9.,           23.,            9.,   9.,    20.,    20.,           9.,  9., 20., 20.] ???
  # dof_effort_limit_list:    [200., 200.,  200.,    300.,  40.,         200., 200., 200., 300.,  40.,             200.,           40.,  40.,  18.,  18.,              40.,  40.,  18.,  18.] ???
  dof_armature_list: [0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, 0.02, 0.02, 0.02,
                      0.02, 0.02, ]
  dof_joint_friction_list: [0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00, 0.00, 0.00,
                      0.00, 0.00, ]
  body_names: ['Pelvis', 
            'L_Hip', 'L_Knee', 'L_Ankle', 'L_Toe', 'R_Hip', 'R_Knee', 'R_Ankle', 'R_Toe', 
            'Torso', 'Spine', 'Chest', 'Neck', 'Head',  
            'L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand', 
            'R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand', ]
              
  terminate_after_contacts_on : ["Pelvis", "Shoulder", "Hip"] # "knee"
  penalize_contacts_on: []
  init_state:
    pos: [0.0, 0.0, 0.89] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles :  # : target angles [rad] when action : 0.0
      left_hip_yaw_joint : 0. 
      left_hip_roll_joint : 0            
      left_hip_pitch_joint : 0.      
      left_knee_joint : 0.    
      left_ankle_joint : 0.  
      right_hip_yaw_joint : 0. 
      right_hip_roll_joint : 0 
      right_hip_pitch_joint : 0.                                    
      right_knee_joint : 0.                                          
      right_ankle_joint : 0.                                  
      torso_joint : 0. 
      left_shoulder_pitch_joint : 0. 
      left_shoulder_roll_joint : 0 
      left_shoulder_yaw_joint : 0.
      left_elbow_joint  : 0.
      right_shoulder_pitch_joint : 0.
      right_shoulder_roll_joint : 0.0
      right_shoulder_yaw_joint : 0.
      right_elbow_joint : 0.
  

  randomize_link_body_names : [
    'Pelvis', 'L_Hip_x', 'L_Hip_y', 'L_Hip_z', 
    'R_Hip_x', 'R_Hip_y', 'R_Hip_z',  'Torso_x', 'Torso_y', 'Torso_z',
  ]
  control:
    control_type: P
    # PD Drive parameters:
    stiffness: 
      Hip: 800
      Knee: 800
      Ankle: 800
      Toe: 500
      Torso: 1000
      Spine: 1000
      Chest: 1000
      Neck: 500
      Head: 500
      Thorax: 500
      Shoulder: 500
      Elbow: 500
      Wrist: 300
      Hand: 300
       # [N*m/rad]

    damping : 
      Hip: 80
      Knee: 80
      Ankle: 80
      Toe: 50
      Torso: 100
      Spine: 100
      Chest: 100
      Neck: 50
      Head: 50
      Thorax: 50
      Shoulder: 50
      Elbow: 50
     # [N*m*s/rad]

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 1
    action_clip_value: 10
    clip_torques: false
  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.02
    max_angular_velocity: 100.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.02
    linear_damping: 0.

    urdf_file: "smpl/${robot.asset.robot_type}.urdf"
    usd_file: "smpl/${robot.asset.robot_type}.usd"
    xml_file: "smpl/${robot.asset.robot_type}.xml"
    robot_type: smpl
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3
    
    
  
  motion:
    motion_file : 'humanoidverse/data/motions/smpl/amass_all.pkl'
    # motion_file : 'humanoidverse/data/motions/g1_29dof/v1/singles/0-ACCAD_Male2General_c3d_A6- Box lift_poses.pkl'
    asset:
      assetRoot: "humanoidverse/data/robots/smpl/"
      # assetFileName: "h1.xml"
      assetFileName: "smpl.xml"
      urdfFileName: "smpl.urdf"

    humanoid_type: smpl
    bias_offset: false
    has_self_collision: true
    has_mesh: false
    has_jt_limit: false
    has_dof_subset: true
    has_upright_start: true
    has_smpl_pd_offset: false
    remove_toe: false # For humanoid's geom toe
    motion_sym_loss: false
    sym_loss_coef: 1
    big_ankle: true

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: false

    masterfoot: true
    freeze_toe: false
    freeze_hand: true
    box_body: true
    real_weight: true
    real_weight_porpotion_capsules: true
    real_weight_porpotion_boxes: true

    body_names: ['Pelvis', 
              'L_Hip', 'L_Knee', 'L_Ankle', 'L_Toe', 'R_Hip', 'R_Knee', 'R_Ankle', 'R_Toe', 
              'Torso', 'Spine', 'Chest', 'Neck', 'Head',  
              'L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand', 
              'R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand', ]
          
    limb_weight_group: 
      - ['L_Hip', 'L_Knee', 'L_Ankle', 'L_Toe']
      - ['R_Hip', 'R_Knee', 'R_Ankle', 'R_Toe']
      - ['Torso', 'Spine', 'Chest', 'Neck', 'Head', ]
      - ['L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand',]
      - ['R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand', ]

    dof_names: ['L_Hip_x', 
              'L_Hip_y', 
              'L_Hip_z', 
              'L_Knee_x', 
              'L_Knee_y',
              'L_Knee_z', 
              'L_Ankle_x', 
              'L_Ankle_y', 
              'L_Ankle_z', 
              'L_Toe_x',
              'L_Toe_y', 
              'L_Toe_z', 
              'R_Hip_x', 
              'R_Hip_y', 
              'R_Hip_z', 
              'R_Knee_x', 
              'R_Knee_y',
              'R_Knee_z', 
              'R_Ankle_x', 
              'R_Ankle_y', 
              'R_Ankle_z', 
              'R_Toe_x',
              'R_Toe_y', 
              'R_Toe_z', 
              'Torso_x',
              'Torso_y', 
              'Torso_z', 
              'Spine_x',
              'Spine_y', 
              'Spine_z', 
              'Chest_x',
              'Chest_y', 
              'Chest_z', 
              'Neck_x',
              'Neck_y', 
              'Neck_z', 
              'Head_x',
              'Head_y', 
              'Head_z', 
              'L_Thorax_x',
              'L_Thorax_y', 
              'L_Thorax_z', 
              'L_Shoulder_x',
              'L_Shoulder_y', 
              'L_Shoulder_z', 
              'L_Elbow_x',
              'L_Elbow_y', 
              'L_Elbow_z', 
              'L_Wrist_x',
              'L_Wrist_y', 
              'L_Wrist_z', 
              'L_Hand_x',
              'L_Hand_y', 
              'L_Hand_z', 
              'R_Thorax_x',
              'R_Thorax_y', 
              'R_Thorax_z', 
              'R_Shoulder_x',
              'R_Shoulder_y', 
              'R_Shoulder_z', 
              'R_Elbow_x',
              'R_Elbow_y', 
              'R_Elbow_z', 
              'R_Wrist_x',
              'R_Wrist_y', 
              'R_Wrist_z', 
              'R_Hand_x',
              'R_Hand_y', 
              'R_Hand_z', ]
              
    right_foot_name: 'R_Ankle'
    left_foot_name: 'L_Ankle'


    nums_extend_bodies: 2
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "L_Hand"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "R_Hand"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      # - joint_name: "head_link"
      #   parent_name: "torso_link"
      #   pos: [0.0, 0.0, 0.42]
      #   rot: [1.0, 0.0, 0.0, 0.0] # w x y z


    motion_tracking_link:
      - "L_Hand"
      - "R_Hand"
      - "Head"

    lower_body_link:
      - "Pelvis"
      - "L_Hip"
      - "L_Knee"
      - "L_Ankle"
      - "L_Toe"
      - "R_Hip"
      - "R_Knee"
      - "R_Ankle"
      - "R_Toe"

    upper_body_link:
      - "Torso"
      - "Spine"
      - "Chest"
      - "Neck"
      - "Head"
      - "L_Thorax"
      - "L_Shoulder"
      - "L_Elbow"
      - "L_Wrist"
      - "L_Hand"
      - "R_Thorax"
      - "R_Shoulder"
      - "R_Elbow"
      - "R_Wrist"
      - "R_Hand"
      - "Head"


    pelvis_link: "Pelvis"
    base_link: "Pelvis"
    hips_link:
      - "L_Hip"
      - "R_Hip"
    

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # pelvis
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_roll_joint
      - [0.929, 0.867, 0.437] # left_hip_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
      # - [0.929, 0.867, 0.437] # left_ankle_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_yaw_joint
      - [0.929, 0.867, 0.437] # right_hip_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      # - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # right_ankle_roll_joint
      # - [0.929, 0.867, 0.437] # waist_yaw_joint
      # - [0.929, 0.867, 0.437] # waist_roll_joint
      - [0.929, 0.867, 0.437] # torso_joint (waist_pitch_link)
      - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0, 0.351, 0.613] # left_elbow_joint_extend
      - [0, 0.351, 0.613] # right_elbow_joint_extend
      - [0, 0.351, 0.613] # head_link

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1