# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 20
  dof_obs_size: 19
  actions_dim: 19
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1

  key_bodies: ["left_ankle_link", "right_ankle_link"]
  contact_bodies: [ "left_ankle_link", "right_ankle_link" ]
  right_foot_name: "right_ankle_link"
  left_foot_name: "left_ankle_link"
  foot_name: "ankle"
  knee_name: "knee_link"
  has_upper_body_dof: True
  has_torso: True
  torso_name: "torso_link"
  # DFS order (isaacgym order)
  dof_names: ['left_hip_yaw_joint', 
              'left_hip_roll_joint', 
              'left_hip_pitch_joint', 
              'left_knee_joint', 
              'left_ankle_joint',
              'right_hip_yaw_joint', 
              'right_hip_roll_joint', 
              'right_hip_pitch_joint', 
              'right_knee_joint', 
              'right_ankle_joint',
              'torso_joint', 
              'left_shoulder_pitch_joint', 
              'left_shoulder_roll_joint', 
              'left_shoulder_yaw_joint', 
              'left_elbow_joint',
              'right_shoulder_pitch_joint', 
              'right_shoulder_roll_joint', 
              'right_shoulder_yaw_joint', 
              'right_elbow_joint']

  decouple_upper_and_lower_dofs: true

  upper_dof_names: ['torso_joint', 
                    'left_shoulder_pitch_joint', 
                    'left_shoulder_roll_joint', 
                    'left_shoulder_yaw_joint', 
                    'left_elbow_joint',
                    'right_shoulder_pitch_joint', 
                    'right_shoulder_roll_joint', 
                    'right_shoulder_yaw_joint', 
                    'right_elbow_joint']
  
  lower_dof_names: ['left_hip_yaw_joint', 
                    'left_hip_roll_joint', 
                    'left_hip_pitch_joint', 
                    'left_knee_joint', 
                    'left_ankle_joint',
                    'right_hip_yaw_joint', 
                    'right_hip_roll_joint', 
                    'right_hip_pitch_joint', 
                    'right_knee_joint', 
                    'right_ankle_joint']
  waist_dof_names: []
  
  # DOF properties
  dof_pos_lower_limit_list: [-0.43, -0.43, -1.57, -0.26, -0.87,       -0.43, -0.43, -1.57, -0.26, -0.87,        -2.35,          -2.87, -0.34, -1.3, -1.25,         -2.87, -3.11, -4.45, -1.25]
  dof_pos_upper_limit_list: [0.43,  0.43,   1.57,  2.05,  0.52,        0.43, 0.43,  1.57,  2.05,   0.52,         2.35,           2.87, 3.11,  4.45,   2.61,          2.87, 0.34, 1.3, 2.61]
  dof_vel_limit_list:       [23.,   23.,    23.,   14.,   9.,          23.,  23.,   23.,  14.,     9.,           23.,            9.,   9.,    20.,    20.,           9.,  9., 20., 20.]
  dof_effort_limit_list:    [200., 200.,  200.,    300.,  40.,         200., 200., 200., 300.,  40.,             200.,           40.,  40.,  18.,  18.,              40.,  40.,  18.,  18.]
  dof_armature_list: [0.1, 0.1, 0.1, 0.1, 0.1,
                      0.1, 0.1, 0.1, 0.1, 0.1,
                      0.1,
                      0.1, 0.1, 0.1, 0.1,
                      0.1, 0.1, 0.1, 0.1]
  dof_joint_friction_list: [0.00, 0.00, 0.00, 0.00, 0.00, 
                            0.00, 0.00, 0.00, 0.00, 0.00,
                            0.00,
                            0.00, 0.00, 0.00, 0.00,
                            0.00, 0.00, 0.00, 0.00]


  body_names: ['pelvis', 
                'left_hip_yaw_link', 'left_hip_roll_link','left_hip_pitch_link', 'left_knee_link', 'left_ankle_link',
                'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link',
                'torso_link', 
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

  terminate_after_contacts_on : ["pelvis", "shoulder", "hip"] # "knee"
  penalize_contacts_on: []
  init_state:
    pos: [0.0, 0.0, 1.05] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles :  # : target angles [rad] when action : 0.0
      left_hip_yaw_joint : 0. 
      left_hip_roll_joint : 0            
      left_hip_pitch_joint : -0.4      
      left_knee_joint : 0.8    
      left_ankle_joint : -0.4  
      right_hip_yaw_joint : 0. 
      right_hip_roll_joint : 0 
      right_hip_pitch_joint : -0.4                                    
      right_knee_joint : 0.8                                          
      right_ankle_joint : -0.4                                  
      torso_joint : 0. 
      left_shoulder_pitch_joint : 0. 
      left_shoulder_roll_joint : 0 
      left_shoulder_yaw_joint : 0.
      left_elbow_joint  : 0.
      right_shoulder_pitch_joint : 0.
      right_shoulder_roll_joint : 0.0
      right_shoulder_yaw_joint : 0.
      right_elbow_joint : 0.
  

  randomize_link_body_names : [
    'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 
    'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link',  'torso_link',
  ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 200
      hip_roll: 200
      hip_pitch: 200
      knee: 300
      ankle: 40
      torso: 300
      shoulder: 100
      elbow : 100 # [N*m/rad]

    damping :
      hip_yaw: 5
      hip_roll: 5
      hip_pitch: 5
      knee: 6
      ankle: 2
      torso: 6
      shoulder: 2
      elbow: 2 # [N*m/rad]  # [N*m*s/rad]

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "h1/${robot.asset.robot_type}.urdf"
    usd_file: "h1/${robot.asset.robot_type}.usd"
    xml_file: "h1/${robot.asset.robot_type}.xml"
    robot_type: h1
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3
    
  motion:
    motion_file : 'humanoidverse/data/motions/g1_29dof_anneal_23dof/v1/amass_all.pkl'
    # motion_file : 'humanoidverse/data/motions/g1_29dof/v1/singles/0-ACCAD_Male2General_c3d_A6- Box lift_poses.pkl'
    asset:
      assetRoot: "humanoidverse/data/robots/h1/"
      # assetFileName: "h1.xml"
      assetFileName: "h1.xml"
      urdfFileName: "h1.urdf"

    humanoid_type: h1
    bias_offset: false
    has_self_collision: true
    has_mesh: false
    has_jt_limit: false
    has_dof_subset: true
    has_upright_start: true
    has_smpl_pd_offset: false
    remove_toe: false # For humanoid's geom toe
    motion_sym_loss: false
    sym_loss_coef: 1
    big_ankle: true

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: false

    masterfoot: true
    freeze_toe: false
    freeze_hand: true
    box_body: true
    real_weight: true
    real_weight_porpotion_capsules: true
    real_weight_porpotion_boxes: true

    body_names: ['pelvis', 
                'left_hip_yaw_link', 'left_hip_roll_link','left_hip_pitch_link', 'left_knee_link', 'left_ankle_link',
                'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link',
                'torso_link', 
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']
          
    limb_weight_group: 
      - ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_link']
      - ['right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_link', ]
      - ['pelvis', 'torso_link']
      - ['left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link']
      - ['right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

    dof_names: ['left_hip_yaw_joint', 
              'left_hip_roll_joint', 
              'left_hip_pitch_joint', 
              'left_knee_joint', 
              'left_ankle_joint',
              'right_hip_yaw_joint', 
              'right_hip_roll_joint', 
              'right_hip_pitch_joint', 
              'right_knee_joint', 
              'right_ankle_joint',
              'torso_joint', 
              'left_shoulder_pitch_joint', 
              'left_shoulder_roll_joint', 
              'left_shoulder_yaw_joint', 
              'left_elbow_joint',
              'right_shoulder_pitch_joint', 
              'right_shoulder_roll_joint', 
              'right_shoulder_yaw_joint', 
              'right_elbow_joint']
    right_foot_name: 'right_ankle_link'
    left_foot_name: 'left_ankle_link'


    nums_extend_bodies: 2
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "left_elbow_link"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "right_elbow_link"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      # - joint_name: "head_link"
      #   parent_name: "torso_link"
      #   pos: [0.0, 0.0, 0.42]
      #   rot: [1.0, 0.0, 0.0, 0.0] # w x y z


    motion_tracking_link:
      - "left_hand_link"
      - "right_hand_link"
      # - "head_link"

    lower_body_link:
      - "pelvis"
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "left_knee_link"
      - "left_ankle_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
      - "right_knee_link"
      - "right_ankle_link"
      - "torso_link"

    upper_body_link:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "left_hand_link"
      - "right_hand_link"
      # - "head_link"


    pelvis_link: "pelvis"
    base_link: "torso_link"
    hips_link:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
    
    joint_matches:
      - ["pelvis", "Pelvis"]
      - ["left_hip_pitch_link", "L_Hip"]
      - ["left_knee_link", "L_Knee"]
      - ["left_ankle_link", "L_Ankle"]
      - ["right_hip_pitch_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["right_ankle_link", "R_Ankle"]
      - ["left_shoulder_roll_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["right_shoulder_roll_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      # - ["head_link", "Head"]


    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      - L_Elbow: "[0, -np.pi/2, 0]"
      - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # pelvis
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_roll_joint
      - [0.929, 0.867, 0.437] # left_hip_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
      # - [0.929, 0.867, 0.437] # left_ankle_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_yaw_joint
      - [0.929, 0.867, 0.437] # right_hip_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      # - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # right_ankle_roll_joint
      # - [0.929, 0.867, 0.437] # waist_yaw_joint
      # - [0.929, 0.867, 0.437] # waist_roll_joint
      - [0.929, 0.867, 0.437] # torso_joint (waist_pitch_link)
      - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0, 0.351, 0.613] # left_elbow_joint_extend
      - [0, 0.351, 0.613] # right_elbow_joint_extend
      - [0, 0.351, 0.613] # head_link

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1

